export const Icons = {
country: require('./countryImg.png'),
MaskGroup: require('./MaskGroup.png'),
plus: require('./plus.png'),
male:require('./male.png'),
female:require('./female.png'),
board:require('./board.png'),
drawer:require('./drawer.png'),
notification:require('./notification.png'),
downArrow:require('./downArrow.png'),
NotificationDashBord:require('./NotificationDashBord.png'),
notificationSpace:require('./notificationSpace.png'),
cancel:require('./cancel.png'),
profile:require('./profile.png'),
switchRole:require('./switchRole.png'),
draft:require('./draft.png'),
pdf:require('./pdf.png'),
subscription:require('./subscription.png'),
about:require('./about.png'),
termAndService:require('./termAndService.png'),
privacy:require('./privacy.png'),
support:require('./support.png'),
delete:require('./delete.png'),
logout:require('./logout.png'),
next:require('./next.png'),
drawerCancel:require('./drawerCancel.png'),
withoutBgLogo:require('./withoutBgLogo.png'),
home_fill:require('./home_fill.png'),
pdfFooter:require('./pdfFooter.png'),
draftFooter:require('./draftFooter.png'),
profileFooter:require('./profileFooter.png'),
textPaper:require('./textPaper.png'),
rightArrow:require('./rightArrow.png'),
paperFile:require('./paperFile.png'),
filter:require('./filter.png'),
arrowLeft:require('./arrowLeft.png'),
fileUpload:require('./fileUpload.png'),
date:require('./date.png'),
dashBoardImg1:require('./dashBoardImg1.png'),
randompaper:require('./randompaper.png'),
regularpaper:require('./regularpaper.png'),
draftpaper:require('./draftpaper.png'),
custompaper:require('./custompaper.png'),
latestNew:require('./latestNew.png'),
// boardlogoImg:require('./boardlogoImg.png'), //
boardImg:require('./boardImg.png'),
mediumImg:require('./mediumImg.png'),
standardImg:require('./standardImg.png'),
megaphone:require('./megaphone.png'),


//// home icon
math:require('./math.png'),
science:require('./science.png'),
hindi:require('./hindi.png'),
sanskrit:require('./sanskrit.png'),
socialscience:require('./socialscience.png'),
english:require('./english.png'),

};