 export const ApiEndPoint = {
        LoGIN:'login-otp',
        LoGINROlE:'login',  
        Question:'question',  
        Board:'boards',
        Medium:'medium',
        Classes:'classes',
        Banner:'banner',
        Subject:'subject',
        UpdateProfile:'update-profile',
        GetProfile:'get-profile',
        bookFetch:'book',
        questionChapter:'question-chapter',
        difficultyLabel :'difficulty-level',
        queationtype :'queation-type',
        updateRole :'update-role',
        draftAdd :'draft-add',
        draftList :'draft-list',
    }
